"""
    Constants
"""
MAX_FPS = 60
MAX_ANIMATION_FRAMES = 4
MAX_FPS_ANIMATION_COUNTS = MAX_FPS / MAX_ANIMATION_FRAMES

FRAME_OFFSET_UP = MAX_ANIMATION_FRAMES * 0
FRAME_OFFSET_DOWN = MAX_ANIMATION_FRAMES * 1
FRAME_OFFSET_LEFT = MAX_ANIMATION_FRAMES * 2
FRAME_OFFSET_RIGHT = MAX_ANIMATION_FRAMES * 3

PLAYER_STARTING_POSITION = [0.0, 0.0]
